version: "3.7"

services:
  rabbitmq:
    image: rabbitmq
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    hostname: rabbit

  rabbitmq-create-infrastructure:
    image: rabbitmq-create-infrastructure
    build:
      context: .
      dockerfile: python.Dockerfile
    depends_on:
      - rabbitmq